version: 1
policy:
  pullRequests: public
tasks:
  $let:
    head_branch:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.ref}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: ${event.release.target_commitish}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
    - provisionerId: aws-provisioner-v1
      workerType: releng-svc
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      extra:
        github:
          events:
            - pull_request.opened
            - pull_request.reopened
            - pull_request.synchronize
            - push
      payload:
        capabilities:
          privileged: true
        env:
          GIT_REPOSITORY: ${repository}
          GIT_REVISION: ${head_rev}
        maxRunTime: 3600
        image: babadie/taskboot:latest
        command:
          - taskboot
          - build
          - Dockerfile
          - --write
          - /image.tar
        artifacts:
          public/taskboot/image.tar:
            expires: {$fromNow: '2 weeks'}
            path: /base.tar
            type: file
      scopes:
        - docker-worker:capability:privileged
      metadata:
        name: TaskBoot Docker build
        description: Taskcluster boot utilities
        owner: bastien@mozilla.com
        source: https://github.com/mozilla/task-boot
