version: 1
policy:
  pullRequests: public
tasks:
  $let:
    head_branch:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.ref}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: ${event.release.target_commitish}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
    - taskId: {$eval: as_slugid("docker_build")}
      provisionerId: aws-provisioner-v1
      workerType: releng-svc
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      extra:
        github:
          events:
            - pull_request.opened
            - pull_request.reopened
            - pull_request.synchronize
            - push
      payload:
        capabilities:
          privileged: true
        maxRunTime: 3600
        image: python:3-alpine
        command:
          - sh
          - -lxce
          - "apk add tar zstd make git img --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing --quiet &&
            git clone --quiet ${repository} /src && cd /src && git checkout ${head_rev} -b taskboot &&
            make taskcluster-build"
        artifacts:
          public/taskboot/image.tar.zst:
            expires: {$fromNow: '2 weeks'}
            path: /image.tar.zst
            type: file
      scopes:
        - docker-worker:capability:privileged
      metadata:
        name: TaskBoot Docker build
        description: Taskcluster boot utilities
        owner: bastien@mozilla.com
        source: https://github.com/mozilla/task-boot

    - taskId: {$eval: as_slugid("docker_test")}
      dependencies:
        - {$eval: as_slugid("docker_build")}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      extra:
        github:
          events:
            - pull_request.opened
            - pull_request.reopened
            - pull_request.synchronize
            - push
      payload:
        capabilities:
          privileged: true
        maxRunTime: 3600
        image:
          type: task-image
          path: public/taskboot/image.tar.zst
          taskId: {$eval: as_slugid("docker_build")}
        env:
          GIT_REPOSITORY: ${repository}
          GIT_REVISION: ${head_rev}
        command:
          - taskboot
          - build
          - tests/dockerfile.empty
      scopes:
        - docker-worker:capability:privileged
      metadata:
        name: TaskBoot Docker image test
        description: Taskcluster boot utilities
        owner: bastien@mozilla.com
        source: https://github.com/mozilla/task-boot
